# Generated by Django 3.0.3 on 2023-03-15 04:38

import cgen.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('WSC', 'Workshop Certificate'), ('TCC', 'Test/Exam Course Certificate')], max_length=400)),
                ('template', models.FileField(blank=True, default=None, help_text='Upload LaTeX template for the certificate', null=True, upload_to=cgen.models.get_file_dir)),
                ('background', models.FileField(blank=True, default=None, help_text='Upload background for the certificate in png or jpg', null=True, upload_to=cgen.models.get_file_dir)),
                ('variables', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(blank=True, default=None, help_text='Upload template for verification', null=True, upload_to=cgen.models.get_file_dir)),
                ('details', models.TextField()),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgen.Certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=1000)),
                ('details', models.TextField()),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgen.Certificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('email', 'certificate')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Start date and time of the Event')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='End date and time of the Event')),
                ('is_published', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.BooleanField(default=False)),
                ('has_downloaded', models.BooleanField(default=False)),
                ('certificate_creation_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('download_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('serial_key_long', models.CharField(default=None, max_length=80, null=True, unique=True)),
                ('serial_key_short', models.CharField(default=None, max_length=80, null=True, unique=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgen.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgen.Event'),
        ),
    ]
