# Generated by Django 4.1.7 on 2023-03-24 00:32

import cgen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatemanager',
            name='certificate_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=cgen.models.get_file_dir),
        ),
    ]
