# Generated by Django 4.1.7 on 2023-03-27 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cgen', '0002_certificatemanager_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatemanager',
            name='certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cgen.certificate'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cgen.event'),
        ),
        migrations.AlterField(
            model_name='certificatemanager',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cgen.participant'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cgen.certificate'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verification',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cgen.certificate'),
        ),
    ]
