# Generated by Django 4.1.7 on 2023-04-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgen', '0004_remove_certificatemanager_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='_type',
        ),
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(default='Particular type of certificate in the event'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
