# Generated by Django 4.1.7 on 2023-10-06 10:53

import cgen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgen', '0005_remove_certificate__type_certificate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='template_type',
            field=models.CharField(choices=[('tex', 'LaTeX Template'), ('svg', 'SVG Template')], default='tex', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificatemanager',
            name='certificate_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=cgen.models.get_certificate_dir),
        ),
    ]
